app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('quiz/', include('quiz.urls')),
]

app/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

app/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'


urlpatterns = [
    path('quiz-categories/', views.QuizCategories.as_view(), name='quiz-categories'),
    path('quiz-exams/<slug:category_slug>/',
         views.QuizExams.as_view(), name='quiz-exams'),
    path('quiz-questions/<slug:quiz_exam_slug>/',
         views.QuizQuestions.as_view(), name='quiz-questions'),

    path('quiz-admin/', views.QuizAdmin.as_view(), name='quiz-admin'),

    path('quiz-admin/quiz-category-add/', views.QuizCategoryCreate.as_view(),
         name='quiz-category-add'),
    path('quiz-admin/quiz-category-list/', views.QuizCategoryList.as_view(),
         name='quiz-category-list'),
    path('quiz-admin/quiz-category-detail/<slug:slug>/',
         views.QuizCategoryDetail.as_view(), name='quiz-category-detail'),
    path('quiz-admin/quiz-category-update/<slug:slug>/',
         views.QuizCategoryUpdate.as_view(), name='quiz-category-update'),
    path('quiz-admin/quiz-category-delete/<slug:slug>/',
         views.QuizCategoryDelete.as_view(), name='quiz-category-delete'),

    path('quiz-admin/quiz-exam-list/',
         views.QuizExamList.as_view(), name='quiz-exam-list'),
    path('quiz-admin/quiz-exam-add/', views.QuizExamCreate.as_view(),
         name='quiz-exam-add'),
    path('quiz-admin/quiz-exam-detail/<slug:slug>/',
         views.QuizExamDetail.as_view(), name='quiz-exam-detail'),
    path('quiz-admin/quiz-exam-update/<slug:slug>/',
         views.QuizExamUpdate.as_view(), name='quiz-exam-update'),
    path('quiz-admin/quiz-exam-delete/<slug:slug>/',
         views.QuizExamDelete.as_view(), name='quiz-exam-delete'),

    path('quiz-admin/quiz-question-add/<slug:quiz_exam_slug>/',
         views.QuizQuestionCreate.as_view(), name='quiz-question-add'),
    path('quiz-admin/quiz-question-list/<slug:quiz_exam_slug>/',
         views.QuizQuestionList.as_view(), name='quiz-question-list'),
    path('quiz-admin/quiz-question-detail/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionDetail.as_view(), name='quiz-question-detail'),
    path('quiz-admin/quiz-question-update/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionUpdate.as_view(), name='quiz-question-update'),
    path('quiz-admin/quiz-question-delete/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionDelete.as_view(), name='quiz-question-delete'),
]

app/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('quiz-result/<int:quiz_exam>/', views.quiz_result, name='quiz-result'),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %}Quiz Application{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Font Awesome-->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% include './header.html' %}
    <div class="container-fluid mt-5">
      <div class="offset-md-2 col-md-8">
        {% block content %} {% endblock content %}
      </div>
    </div>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block extra_js %}
    {% endblock extra_js %}
  </body>
</html>

app/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'core:home' %}">Quiz Application</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:quiz-admin' %}">Admin</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:profile' username=request.user.username %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </container>
    </nav>
</header>

app/templates/index.html
{% extends './base.html' %}

{% block content %}
    <div class="col-md-12">
        {% include './messages_and_errors.html' %}
    </div>
    <div class="col-md-12">
        <div class="text-center category__title my-2">Quiz Categories</div>
        <hr />
        {% if categories %}
            <div class="row">
                {% for category in categories %}
                    <div class="col-md-4 category__div">
                        <a href="{% url 'quiz:quiz-exams' category_slug=category.slug %}"><div class="category__name">{{category.name}}</div></a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center">No quiz categories yet!</div>
        {% endif %}
    </div>
{% endblock content %}

app/templates/messages_and_errors.html
{% if messages %}
	<div class="mt-2 text-center wow fadeInRight">
		{% for message in messages %}
			{% if message.tags == 'error' %}
				<div class="alert alert-danger alert-auto-dismiss">
			{% elif message.tags == 'success' %}
				<div class="alert alert-success alert-auto-dismiss">
			{% elif message.tags == 'warning' %}
				<div class="alert alert-warning alert-auto-dismiss">
			{% else %}
				<div class="alert alert-info alert-auto-dismiss">
			{% endif %}
				<a class="close" href="#" data-dismiss="alert">x</a>
				{{message}}
			</div>
		{% endfor %}
	</div>
{% endif %}