app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('user.urls')),
    path('quiz/', include('quiz.urls')),
]

app/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'


urlpatterns = [
    path('quiz-categories/', views.QuizCategories.as_view(), name='quiz-categories'),
    path('quiz-exams/<slug:category_slug>/',
         views.QuizExams.as_view(), name='quiz-exams'),
    path('quiz-questions/<slug:quiz_exam_slug>/',
         views.QuizQuestions.as_view(), name='quiz-questions'),

    path('quiz-admin/', views.QuizAdmin.as_view(), name='quiz-admin'),

    path('quiz-admin/quiz-category-add/', views.QuizCategoryCreate.as_view(),
         name='quiz-category-add'),
    path('quiz-admin/quiz-category-list/', views.QuizCategoryList.as_view(),
         name='quiz-category-list'),
    path('quiz-admin/quiz-category-detail/<slug:slug>/',
         views.QuizCategoryDetail.as_view(), name='quiz-category-detail'),
    path('quiz-admin/quiz-category-update/<slug:slug>/',
         views.QuizCategoryUpdate.as_view(), name='quiz-category-update'),
    path('quiz-admin/quiz-category-delete/<slug:slug>/',
         views.QuizCategoryDelete.as_view(), name='quiz-category-delete'),

    path('quiz-admin/quiz-exam-list/',
         views.QuizExamList.as_view(), name='quiz-exam-list'),
    path('quiz-admin/quiz-exam-add/', views.QuizExamCreate.as_view(),
         name='quiz-exam-add'),
    path('quiz-admin/quiz-exam-detail/<slug:slug>/',
         views.QuizExamDetail.as_view(), name='quiz-exam-detail'),
    path('quiz-admin/quiz-exam-update/<slug:slug>/',
         views.QuizExamUpdate.as_view(), name='quiz-exam-update'),
    path('quiz-admin/quiz-exam-delete/<slug:slug>/',
         views.QuizExamDelete.as_view(), name='quiz-exam-delete'),

    path('quiz-admin/quiz-question-add/<slug:quiz_exam_slug>/',
         views.QuizQuestionCreate.as_view(), name='quiz-question-add'),
    path('quiz-admin/quiz-question-list/<slug:quiz_exam_slug>/',
         views.QuizQuestionList.as_view(), name='quiz-question-list'),
    path('quiz-admin/quiz-question-detail/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionDetail.as_view(), name='quiz-question-detail'),
    path('quiz-admin/quiz-question-update/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionUpdate.as_view(), name='quiz-question-update'),
    path('quiz-admin/quiz-question-delete/<slug:quiz_exam_slug>/<int:pk>/',
         views.QuizQuestionDelete.as_view(), name='quiz-question-delete'),
]

app/quiz/models.py
from django.db import models
from django.db.models.fields.related import ManyToManyField
from django.utils.text import slugify
from jsonfield import JSONField

from core.models import BaseModel
from user.models import User

# Data backup and restore
# python manage.py dumpdata quiz.Category quiz.QuizExam quiz.Question quiz.Option > db.json
# python manage.py loaddata db.json


class Category(BaseModel):
    name = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['created_at']
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class QuizExam(BaseModel):
    name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['name', 'category']
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Question(BaseModel):
    name = models.CharField(max_length=255)
    quiz_exam = models.ForeignKey(QuizExam, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['name', 'quiz_exam']
        ordering = ['created_at']

    def __str__(self):
        return self.name

class Option(BaseModel):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='options')
    name = models.CharField(max_length=255)
    isAnswer = models.BooleanField(default=False)

    class Meta:
        unique_together = ['question', 'name', 'isAnswer']
        ordering = ['created_at']

    def __str__(self):
        return self.question.name


class UserResponse(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz_exam = models.ForeignKey(QuizExam, on_delete=models.CASCADE)
    score = models.IntegerField()
    attempted = models.PositiveBigIntegerField(default=0)
    response = JSONField()

    class Meta:
        unique_together = ['user', 'quiz_exam']
        ordering = ['created_at']

    def __str__(self):
        return self.user.email

app/quiz/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.db.models import F, Count

from .models import Category, QuizExam, Question, Option, UserResponse
from core.utils import StaffMemberRequiredMixin


class QuizAdmin(StaffMemberRequiredMixin, TemplateView):
    template_name = 'quiz/admin.html'


class QuizCategoryList(StaffMemberRequiredMixin, ListView):
    model = Category
    paginate_by = 4
    context_object_name = 'quiz_categories'
    template_name = 'quiz/category/quiz-category-list.html'


class QuizCategoryDetail(StaffMemberRequiredMixin, DetailView):
    model = Category
    template_name = 'quiz/category/quiz-category-detail.html'
    context_object_name = 'quiz_category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class QuizCategoryCreate(StaffMemberRequiredMixin, CreateView):
    model = Category
    fields = ['name']
    #success_url = reverse_lazy('quiz:quiz-category-list')
    template_name = 'quiz/category/quiz-category-form.html'

    def get_success_url(self):
        messages.success(self.request, 'Quiz category created!')
        return reverse('quiz:quiz-category-list')


class QuizCategoryUpdate(StaffMemberRequiredMixin, UpdateView):
    model = Category
    fields = ['name']
    #success_url = reverse_lazy('quiz:quiz-category-list')
    template_name = 'quiz/category/quiz-category-update.html'

    def get_success_url(self):
        messages.info(self.request, 'Quiz category updated!')
        return reverse('quiz:quiz-category-list')


class QuizCategoryDelete(StaffMemberRequiredMixin, DeleteView):
    model = Category
    context_object_name = 'quiz_category'
    #success_url = reverse_lazy('quiz:quiz-category-list')
    template_name = 'quiz/category/quiz-category-delete.html'

    def get_success_url(self):
        messages.error(self.request, 'Quiz category deleted!')
        return reverse('quiz:quiz-category-list')


class QuizExamList(StaffMemberRequiredMixin, ListView):
    model = QuizExam
    paginate_by = 4
    context_object_name = 'quiz_exams'
    template_name = 'quiz/exam/quiz-exam-list.html'

    def get_queryset(self):
        qs = super().get_queryset().select_related('category')
        return qs


class QuizExamDetail(StaffMemberRequiredMixin, DetailView):
    model = QuizExam
    template_name = 'quiz/exam/quiz-exam-detail.html'
    context_object_name = 'quiz_exam'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def get_queryset(self):
        qs = super().get_queryset().select_related('category')
        return qs


class QuizExamCreate(StaffMemberRequiredMixin, CreateView):
    model = QuizExam
    fields = ['name', 'category']
    template_name = 'quiz/exam/quiz-exam-form.html'

    def get_success_url(self):
        messages.success(self.request, 'Quiz exam created!')
        return reverse('quiz:quiz-exam-list')


class QuizExamUpdate(StaffMemberRequiredMixin, UpdateView):
    model = QuizExam
    fields = ['name', 'category']
    template_name = 'quiz/exam/quiz-exam-update.html'

    def get_success_url(self):
        messages.info(self.request, 'Quiz exam updated!')
        return reverse('quiz:quiz-exam-list')


class QuizExamDelete(StaffMemberRequiredMixin, DeleteView):
    model = QuizExam
    context_object_name = 'quiz_exam'
    template_name = 'quiz/exam/quiz-exam-delete.html'

    def get_success_url(self):
        messages.error(self.request, 'Quiz exam deleted!')
        return reverse('quiz:quiz-exam-list')


class QuizCategories(View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        return render(request, 'quiz/quiz-categories.html', {'categories': categories})


class QuizExams(View):
    def get(self, request, *args, **kwargs):
        category_slug = kwargs.get('category_slug')
        category = None
        if category_slug:
            try:
                category = Category.objects.get(slug=category_slug)
            except:
                pass
            quiz_exams = QuizExam.objects.filter(
                category__slug__icontains=category_slug)
        else:
            quiz_exams = []
        return render(request, 'quiz/quiz-exams.html', {'quiz_exams': quiz_exams, 'category': category})


class QuizQuestions(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        quiz_exam_slug = kwargs.get('quiz_exam_slug')
        if quiz_exam_slug:
            questions = Question.objects.filter(quiz_exam__slug__iexact=quiz_exam_slug).prefetch_related('options')
        else:
            questions = []
        return render(request, 'quiz/quiz-questions.html', {'questions': questions, 'quiz_exam_slug': quiz_exam_slug})

    def post(self, request, *args, **kwargs):
        data = dict(request.POST)
        quiz_exam = QuizExam.objects.get(slug=kwargs.get('quiz_exam_slug'))
        score = 0
        del data['csrfmiddlewaretoken']
        questions = Question.objects.filter(id__in=data.keys()).prefetch_related('options')
        for question, answer in zip(questions, data.values()):
            answer_count = len(answer)
            answer_count_check = 0
            for option in question.options.all():
                if str(option.id) in answer and option.isAnswer:
                    answer_count_check += 1
            if answer_count == answer_count_check:
                score += 1
        user_response, created = UserResponse.objects.get_or_create(
            user=request.user,
            quiz_exam=quiz_exam,
            defaults={
                'score': score,
                'response': data,
                'attempted': 1
            }
        )
        if not created:
            user_response.score = score
            user_response.response = data
            user_response.attempted += 1
            user_response.save()
        return render(
            request,
            'quiz/response.html',
            {
                'message': 'Your quiz has been submitted. Click the following link to view your result!',
                'quiz_exam': quiz_exam.id
            }
        )


class QuizQuestionList(ListView):
    model = Question
    paginate_by = 5
    context_object_name = 'questions'
    template_name = 'quiz/question/quiz-question-list.html'

    def get_queryset(self):
        qs = super().get_queryset().select_related('quiz_exam')
        return qs.filter(quiz_exam__slug=self.kwargs.get('quiz_exam_slug'))

    def get_context_data(self):
        data = super().get_context_data()
        data['quiz_exam_slug'] = self.kwargs.get('quiz_exam_slug')
        return data


class QuizQuestionDetail(View):
    template_name = 'quiz/question/quiz-question-detail.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'question': Question.objects.get(
            id=kwargs.get('pk')), 'quiz_exam_slug': kwargs.get('quiz_exam_slug')})


class QuizQuestionCreate(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quiz/question/quiz-question-form.html', {})

    def post(self, request, *args, **kwargs):
        quiz_exam = QuizExam.objects.get(slug=kwargs.get('quiz_exam_slug'))
        data = dict(request.POST)
        # print(data)
        if data.get('question') == ['']:
            messages.error(request, 'Question field should not be empty!')
        elif data.get('option1') is None or data.get('option1') == ['']:
            messages.error(
                request, 'Please provide question with at least two options!')
        elif data.get('option2') is None or data.get('option2') == ['']:
            messages.error(
                request, 'Please provide question with at least two options!')
        else:
            for key, value in data.items():
                if key == 'csrfmiddlewaretoken':
                    continue
                if key == 'question':
                    question, created = Question.objects.get_or_create(
                        **{'name': value[0], 'quiz_exam': quiz_exam})
                    if created:
                        continue
                    else:
                        messages.error(
                            request, 'Duplicate question, question already in database!')
                        return render(request, 'quiz/question/quiz-question-form.html', {})
                try:
                    value_length = len(value)
                    if value_length > 1:
                        option, created = Option.objects.get_or_create(
                            **{'question': question, 'name': value[1]}, **{'isAnswer': True})
                    else:
                        option, created = Option.objects.get_or_create(
                            **{'question': question, 'name': value[0]}, **{'isAnswer': False})
                except:
                    pass
            messages.success(request, 'Question added successfully')
        return render(request, 'quiz/question/quiz-question-form.html', {})


class QuizQuestionUpdate(View):
    template_name = 'quiz/question/quiz-question-update.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'question': Question.objects.get(id=kwargs.get('pk'))})

    def post(self, request, *args, **kwargs):
        data = dict(request.POST)
        # print(data)
        for key, value in data.items():
            if key == 'csrfmiddlewaretoken':
                continue
            if key == 'question':

app/templates/quiz/exam/quiz-exam-delete.html
{% extends '../../base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block content %}
    <div class="col-md-12">
        <h3 class="text-center my-4">Delete Quiz Exam</h3>
        <form method="post">{% csrf_token %}
            <h5 class="my-2">Are you sure you want to delete "{{ quiz_exam.name }}"?</h5>
            <input type="submit" value="Confirm" class="btn btn-danger pull-right">
        </form>
    </div>
{% endblock %}

app/templates/quiz/exam/quiz-exam-detail.html
{% extends '../../base.html' %}
{% load crispy_forms_tags %}

{% load static %}


{% block content %}
    <div class="col-md-12">
        <h3 class="text-center my-4">Quiz Exam Detail</h3>
        <h6 class="card text-center shadow p-2 mb-4">
            {{ quiz_exam.name }}
            <br />
            Category: {{ quiz_exam.category.name }}
        </h6>
        <a href={% url 'quiz:quiz-exam-update' slug=quiz_exam.slug %}><button class="btn btn-warning pull-right">Update</button></a>
    </div>
{% endblock %}

app/templates/quiz/exam/quiz-exam-form.html
{% extends '../../base.html' %}
{% load crispy_forms_tags %}

{% load static %}


{% block content %}
    <div class="col-md-12">
        <h3 class="text-center">Add Quiz Exam</h3>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save" class="btn btn-success pull-right">
        </form>
    </div>
{% endblock %}

app/templates/quiz/exam/quiz-exam-list.html
{% extends '../../base.html' %}
{% load crispy_forms_tags %}

{% load static %}


{% block content %}
    <div class="col-md-12">
        {% include '../../messages_and_errors.html' %}
    </div>
    <div class="col-md-12">
        <h3 class="text-center">Quiz Exam List</h3>
        <div>
            <table class="table table-bordered table-striped table-hover table-responsive">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">SN</th>
                        <th scope="col" class="text-center">Name</th>
                        <th scope="col" class="text-center">Category</th>
                        <th scope="col" class="text-center" colspan="4"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for quiz_exam in quiz_exams %}
                    <tr>
                        <th scope="row" class="text-center">{{forloop.counter}}</th>
                        <td class="text-center">{{quiz_exam.name}}</td>
                        <td class="text-center">{{quiz_exam.category.name}}</td>
                        <td class="text-center"><a href={% url 'quiz:quiz-exam-detail' slug=quiz_exam.slug %}><button
                                    class="btn btn-info">Detail</button></a></td>
                        <td class="text-center"><a href={% url 'quiz:quiz-exam-update' slug=quiz_exam.slug %}><button
                                    class="btn btn-warning">Update</button></a></td>
                        <td class="text-center"><a href={% url 'quiz:quiz-exam-delete' slug=quiz_exam.slug %}><button
                                    class="btn btn-danger">Delete</button></a></td>
                        <td class"text-center"><a href={% url 'quiz:quiz-question-list' quiz_exam_slug=quiz_exam.slug %}><button class="btn btn-success">Questions</button></a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7" class="text-center">No Quiz Exams yet!</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            <div>
                <a href={% url 'quiz:quiz-exam-add' %}><button class="btn btn-success"><span><i class="fa fa-plus mr-1"></i>Exam</span></button></a>
            </div>
            <br>

            {% if is_paginated%}
            <nav aria-label="Page navigation example">
                <ul class="pagination" style="justify-content: center;">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}
                    
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                        <li class="active page-item"><a class="page-link" href="#"><span>{{ i }}</span></a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/quiz/exam/quiz-exam-update.html
{% extends '../../base.html' %}
{% load crispy_forms_tags %}

{% load static %}


{% block content %}
    <div class="col-md-12">
        <h3 class="text-center">Update Quiz Exam</h3>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Update" class="btn btn-warning pull-right">
        </form>
    </div>
{% endblock %}